pipeline {
    agent any
    environment {
        RELEASE='0.0.1'
    }

    stages {
        stage('Build') {
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
            }
        }
        stage('Test') {
            steps {
                echo "Testing release ${RELEASE}"
            }
        }

        stage('Deploy') {
            input {
                message "Deploy?"
                ok "do it!"
                parameters {
                    string(
                        name: 'TARGET_ENVIRONMENT',
                        defaultValue: 'PROD',
                        description: 'Target environment for deployment'
                    )
                }
            }
            steps {
                echo "Deploying release ${RELEASE} ${TARGET_ENVIRONMENT} environment"
            }
        }

        post {
            always {
                echo "Print whether deployment happened or not."
            }
        }

    }
}